/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author nguye
 */
public class DangNhap_GUI extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap_GUI
     */
    public DangNhap_GUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dangNhap_btn = new javax.swing.JButton();
        taiKhoan_lbl = new javax.swing.JLabel();
        matKhau_lbl = new javax.swing.JLabel();
        taiKhoan_txt = new javax.swing.JTextField();
        matKhau_txt = new javax.swing.JPasswordField();
        quenMatKhau_lbl = new javax.swing.JLabel();
        title_lbl = new javax.swing.JLabel();
        bg_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dangNhap_btn.setBackground(new java.awt.Color(72, 160, 255));
        dangNhap_btn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        dangNhap_btn.setForeground(new java.awt.Color(255, 255, 255));
        dangNhap_btn.setText("Đăng nhập");
        dangNhap_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 160, 255), 3, true));
        dangNhap_btn.setBorderPainted(false);
        dangNhap_btn.setName(""); // NOI18N
        dangNhap_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangNhap_btnActionPerformed(evt);
            }
        });
        jPanel1.add(dangNhap_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 130, 40));

        taiKhoan_lbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        taiKhoan_lbl.setForeground(new java.awt.Color(116, 116, 116));
        taiKhoan_lbl.setText("Tài khoản:");
        jPanel1.add(taiKhoan_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 85, -1, -1));

        matKhau_lbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        matKhau_lbl.setForeground(new java.awt.Color(116, 116, 116));
        matKhau_lbl.setText("Mật khẩu:");
        jPanel1.add(matKhau_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 118, 94, -1));

        taiKhoan_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taiKhoan_txtActionPerformed(evt);
            }
        });
        jPanel1.add(taiKhoan_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 85, 244, 27));

        matKhau_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matKhau_txtActionPerformed(evt);
            }
        });
        jPanel1.add(matKhau_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 118, 244, 27));

        quenMatKhau_lbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        quenMatKhau_lbl.setForeground(new java.awt.Color(116, 116, 116));
        quenMatKhau_lbl.setText("Quên mật khẩu?");
        jPanel1.add(quenMatKhau_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 120, -1));

        title_lbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\NetBeansProjects\\CT-QUAN-LY-DU-AN-HIEU-THUOC-TAY\\QuanLyHieuThuoc\\image\\title.png")); // NOI18N
        jPanel1.add(title_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 270, 80));

        bg_lbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\NetBeansProjects\\CT-QUAN-LY-DU-AN-HIEU-THUOC-TAY\\QuanLyHieuThuoc\\image\\BG_tách nền.png")); // NOI18N
        bg_lbl.setToolTipText("");
        jPanel1.add(bg_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taiKhoan_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taiKhoan_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taiKhoan_txtActionPerformed

    private void matKhau_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matKhau_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matKhau_txtActionPerformed

    private void dangNhap_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangNhap_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dangNhap_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_lbl;
    private javax.swing.JButton dangNhap_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel matKhau_lbl;
    private javax.swing.JPasswordField matKhau_txt;
    private javax.swing.JLabel quenMatKhau_lbl;
    private javax.swing.JLabel taiKhoan_lbl;
    private javax.swing.JTextField taiKhoan_txt;
    private javax.swing.JLabel title_lbl;
    // End of variables declaration//GEN-END:variables
}
