/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.json.JSONArray;
import org.json.JSONObject;
import org.json.JSONTokener;

/**
 *
 * @author nguye
 */
public class KhachHang_GUI extends javax.swing.JPanel {

    private JSONArray data;

    /**
     * Creates new form KhachHang_GUI
     */
    public KhachHang_GUI() {
        initComponents();
        loadData();  // Tải dữ liệu từ file JSON khi khởi tạo
        loadTinhComboBox();  // Hiển thị dữ liệu vào tinhComboBox
        jDialog_them.setSize(600, 450); // Set the size of the dialog
        jDialog_them.setLocationRelativeTo(null); // Center the dialog on the screen
        jDialog_them.setModal(true); // Make the dialog modal if needed
        fileChoser.setSize(600, 450); // Set the size of the dialogSS
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_them = new javax.swing.JDialog();
        ten_txt = new javax.swing.JTextField();
        themKH_btn = new javax.swing.JButton();
        thongTinKhachHang_lbl = new javax.swing.JLabel();
        ten_lbl = new javax.swing.JLabel();
        sdt_txt = new javax.swing.JTextField();
        sdt_lbl = new javax.swing.JLabel();
        ngaySinh_date = new com.toedter.calendar.JDateChooser();
        ngaySinh_lbl = new javax.swing.JLabel();
        diaChiPanel = new javax.swing.JPanel();
        quanComboBox = new javax.swing.JComboBox<>();
        tinhThanh_lbl = new javax.swing.JLabel();
        tinhComboBox = new javax.swing.JComboBox<>();
        quanHuyen_lbl = new javax.swing.JLabel();
        phuongComboBox = new javax.swing.JComboBox<>();
        phuongXa_lbl = new javax.swing.JLabel();
        diaChi_lbl = new javax.swing.JLabel();
        gioiTinh_lbl = new javax.swing.JLabel();
        gioiTinh_cbo = new javax.swing.JComboBox<>();
        themThuoc_btn1 = new javax.swing.JButton();
        fileChoser = new javax.swing.JFileChooser();
        khachHangPanel = new javax.swing.JPanel();
        quanLy = new javax.swing.JLabel();
        khachHangScollPane = new javax.swing.JScrollPane();
        khachHang_table = new javax.swing.JTable();
        north = new javax.swing.JPanel();
        quanLyKhachHang_lbl = new javax.swing.JLabel();
        tim_txt = new javax.swing.JTextField();
        themcsv_btn = new javax.swing.JButton();
        tim_btn = new javax.swing.JButton();
        them_btn = new javax.swing.JButton();

        jDialog_them.setTitle("Thêm nhân viên");
        jDialog_them.setBackground(new java.awt.Color(255, 255, 255));
        jDialog_them.setForeground(new java.awt.Color(255, 255, 255));

        ten_txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ten_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten_txtActionPerformed(evt);
            }
        });

        themKH_btn.setBackground(new java.awt.Color(77, 189, 116));
        themKH_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        themKH_btn.setForeground(new java.awt.Color(255, 255, 255));
        themKH_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\NetBeansProjects\\CT-QUAN-LY-DU-AN-HIEU-THUOC-TAY\\QuanLyHieuThuoc\\image\\plus-24.png")); // NOI18N
        themKH_btn.setText("Thêm");
        themKH_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themKH_btnActionPerformed(evt);
            }
        });

        thongTinKhachHang_lbl.setBackground(new java.awt.Color(255, 255, 255));
        thongTinKhachHang_lbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        thongTinKhachHang_lbl.setText("Thông tin khách hàng");

        ten_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ten_lbl.setText("Tên khách hàng");

        sdt_txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sdt_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdt_txtActionPerformed(evt);
            }
        });

        sdt_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sdt_lbl.setText("Điện thoại");

        ngaySinh_date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ngaySinh_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ngaySinh_lbl.setText("Ngày sinh");

        diaChiPanel.setBackground(new java.awt.Color(255, 255, 255));
        diaChiPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        diaChiPanel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        quanComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        quanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn quận huyện--" }));
        quanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanComboBoxActionPerformed(evt);
            }
        });

        tinhThanh_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tinhThanh_lbl.setText("Tỉnh thành");

        tinhComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tinhComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn tỉnh thành--" }));

        quanHuyen_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        quanHuyen_lbl.setText("Quận huyện");

        phuongComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phuongComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn phường xã--" }));
        phuongComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phuongComboBoxActionPerformed(evt);
            }
        });

        phuongXa_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phuongXa_lbl.setText("Phường xã");

        diaChi_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        diaChi_lbl.setText("Địa chỉ");

        javax.swing.GroupLayout diaChiPanelLayout = new javax.swing.GroupLayout(diaChiPanel);
        diaChiPanel.setLayout(diaChiPanelLayout);
        diaChiPanelLayout.setHorizontalGroup(
            diaChiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaChiPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(diaChiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaChiPanelLayout.createSequentialGroup()
                        .addComponent(tinhThanh_lbl)
                        .addGap(269, 269, 269))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaChiPanelLayout.createSequentialGroup()
                        .addComponent(phuongXa_lbl)
                        .addGap(268, 268, 268))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaChiPanelLayout.createSequentialGroup()
                        .addComponent(quanHuyen_lbl)
                        .addGap(258, 258, 258))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaChiPanelLayout.createSequentialGroup()
                        .addGroup(diaChiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tinhComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(diaChiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(quanComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 225, Short.MAX_VALUE)
                                .addComponent(phuongComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(diaChi_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(131, 131, 131))))
        );
        diaChiPanelLayout.setVerticalGroup(
            diaChiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaChiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(diaChi_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tinhThanh_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tinhComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quanHuyen_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phuongXa_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phuongComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gioiTinh_lbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        gioiTinh_lbl.setText("Giới tính");

        gioiTinh_cbo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gioiTinh_cbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn giới tính--", "Nam", "Nữ" }));
        gioiTinh_cbo.setBorder(null);
        gioiTinh_cbo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gioiTinh_cbo.setPreferredSize(new java.awt.Dimension(80, 22));

        themThuoc_btn1.setBackground(new java.awt.Color(189, 189, 189));
        themThuoc_btn1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        themThuoc_btn1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\NetBeansProjects\\CT-QUAN-LY-DU-AN-HIEU-THUOC-TAY\\QuanLyHieuThuoc\\image\\Github-Octicons-X-16.24.png")); // NOI18N
        themThuoc_btn1.setText("Hủy");

        javax.swing.GroupLayout jDialog_themLayout = new javax.swing.GroupLayout(jDialog_them.getContentPane());
        jDialog_them.getContentPane().setLayout(jDialog_themLayout);
        jDialog_themLayout.setHorizontalGroup(
            jDialog_themLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_themLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jDialog_themLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ten_lbl)
                    .addComponent(diaChiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ten_txt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jDialog_themLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sdt_txt)
                    .addComponent(sdt_lbl)
                    .addComponent(ngaySinh_lbl)
                    .addComponent(ngaySinh_date, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(gioiTinh_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gioiTinh_cbo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_themLayout.createSequentialGroup()
                        .addComponent(themThuoc_btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(themKH_btn)))
                .addGap(17, 17, 17))
            .addGroup(jDialog_themLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thongTinKhachHang_lbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog_themLayout.setVerticalGroup(
            jDialog_themLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_themLayout.createSequentialGroup()
                .addComponent(thongTinKhachHang_lbl)
                .addGap(18, 18, 18)
                .addGroup(jDialog_themLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ten_lbl)
                    .addComponent(sdt_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_themLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ten_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_themLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog_themLayout.createSequentialGroup()
                        .addComponent(diaChiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDialog_themLayout.createSequentialGroup()
                        .addComponent(ngaySinh_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ngaySinh_date, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gioiTinh_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gioiTinh_cbo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDialog_themLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(themKH_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(themThuoc_btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        khachHangPanel.setBackground(new java.awt.Color(255, 255, 255));
        khachHangPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        quanLy.setBackground(new java.awt.Color(199, 199, 199));
        quanLy.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        quanLy.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\NetBeansProjects\\CT-QUAN-LY-DU-AN-HIEU-THUOC-TAY\\QuanLyHieuThuoc\\image\\Amitjakhu-Drip-Menu.24.png")); // NOI18N
        quanLy.setText("   Quản lý khách hàng");

        khachHang_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        khachHangScollPane.setViewportView(khachHang_table);

        javax.swing.GroupLayout khachHangPanelLayout = new javax.swing.GroupLayout(khachHangPanel);
        khachHangPanel.setLayout(khachHangPanelLayout);
        khachHangPanelLayout.setHorizontalGroup(
            khachHangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khachHangPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(khachHangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(khachHangPanelLayout.createSequentialGroup()
                        .addComponent(quanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 1081, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addComponent(khachHangScollPane))
                .addContainerGap())
        );
        khachHangPanelLayout.setVerticalGroup(
            khachHangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khachHangPanelLayout.createSequentialGroup()
                .addComponent(quanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(khachHangScollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        quanLy.getAccessibleContext().setAccessibleDescription("");

        add(khachHangPanel, java.awt.BorderLayout.CENTER);

        quanLyKhachHang_lbl.setBackground(new java.awt.Color(255, 255, 255));
        quanLyKhachHang_lbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyKhachHang_lbl.setForeground(new java.awt.Color(72, 160, 255));
        quanLyKhachHang_lbl.setText("Quản lý khách hàng");

        tim_txt.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tim_txt.setForeground(new java.awt.Color(189, 189, 189));
        tim_txt.setText("Tên, Điện thoại");
        tim_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tim_txtFocusGained(evt);
            }
        });
        tim_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tim_txtActionPerformed(evt);
            }
        });

        themcsv_btn.setBackground(new java.awt.Color(72, 160, 255));
        themcsv_btn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        themcsv_btn.setForeground(new java.awt.Color(255, 255, 255));
        themcsv_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\NetBeansProjects\\CT-QUAN-LY-DU-AN-HIEU-THUOC-TAY\\QuanLyHieuThuoc\\image\\Fatcow-Farm-Fresh-Page-white-excel.24.png")); // NOI18N
        themcsv_btn.setText("Thêm từ excel");
        themcsv_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themcsv_btnActionPerformed(evt);
            }
        });

        tim_btn.setBackground(new java.awt.Color(77, 189, 116));
        tim_btn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tim_btn.setForeground(new java.awt.Color(255, 255, 255));
        tim_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\NetBeansProjects\\CT-QUAN-LY-DU-AN-HIEU-THUOC-TAY\\QuanLyHieuThuoc\\image\\Custom-Icon-Design-Pretty-Office-2-Search.24.png")); // NOI18N
        tim_btn.setText("Tìm kiếm");
        tim_btn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tim_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tim_btnActionPerformed(evt);
            }
        });

        them_btn.setBackground(new java.awt.Color(199, 199, 199));
        them_btn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        them_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\NetBeansProjects\\CT-QUAN-LY-DU-AN-HIEU-THUOC-TAY\\QuanLyHieuThuoc\\image\\Microsoft-Fluentui-Emoji-Mono-Plus.24.png")); // NOI18N
        them_btn.setText("Thêm khách hàng");
        them_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout northLayout = new javax.swing.GroupLayout(north);
        north.setLayout(northLayout);
        northLayout.setHorizontalGroup(
            northLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, northLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tim_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tim_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(them_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themcsv_btn)
                .addGap(7, 7, 7))
            .addGroup(northLayout.createSequentialGroup()
                .addComponent(quanLyKhachHang_lbl)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        northLayout.setVerticalGroup(
            northLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, northLayout.createSequentialGroup()
                .addComponent(quanLyKhachHang_lbl)
                .addGap(13, 13, 13)
                .addGroup(northLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tim_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(northLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(them_btn)
                        .addComponent(themcsv_btn)
                        .addComponent(tim_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        add(north, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void tim_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tim_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tim_txtActionPerformed

    private void tim_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tim_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tim_btnActionPerformed

    private void themcsv_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themcsv_btnActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV Files", "csv");
        fileChoser.setFileFilter(filter);
        fileChoser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = fileChoser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            // Lấy đường dẫn file được chọn
            File selectedFile = fileChoser.getSelectedFile();
            System.out.println(selectedFile.getAbsolutePath());
        } else {
            System.out.println("User cancel");
        }
    }//GEN-LAST:event_themcsv_btnActionPerformed

    private void them_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them_btnActionPerformed
        // TODO add your handling code here:
        jDialog_them.setVisible(true);
    }//GEN-LAST:event_them_btnActionPerformed

    private void ten_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ten_txtActionPerformed

    private void themKH_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themKH_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_themKH_btnActionPerformed

    private void sdt_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdt_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdt_txtActionPerformed

    private void quanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quanComboBoxActionPerformed

    private void phuongComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phuongComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phuongComboBoxActionPerformed

    private void tim_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tim_txtFocusGained
        // TODO add your handling code here:
        if (tim_txt.getText().equals("Tên, Điện thoại")) {
            tim_txt.setText(""); // Xóa placeholder khi người dùng bắt đầu nhập
            tim_txt.setForeground(Color.BLACK); // Đặt màu văn bản về màu đen"
        }
    }//GEN-LAST:event_tim_txtFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel diaChiPanel;
    private javax.swing.JLabel diaChi_lbl;
    private javax.swing.JFileChooser fileChoser;
    private javax.swing.JComboBox<String> gioiTinh_cbo;
    private javax.swing.JLabel gioiTinh_lbl;
    private javax.swing.JDialog jDialog_them;
    private javax.swing.JPanel khachHangPanel;
    private javax.swing.JScrollPane khachHangScollPane;
    private javax.swing.JTable khachHang_table;
    private com.toedter.calendar.JDateChooser ngaySinh_date;
    private javax.swing.JLabel ngaySinh_lbl;
    private javax.swing.JPanel north;
    private javax.swing.JComboBox<String> phuongComboBox;
    private javax.swing.JLabel phuongXa_lbl;
    private javax.swing.JComboBox<String> quanComboBox;
    private javax.swing.JLabel quanHuyen_lbl;
    private javax.swing.JLabel quanLy;
    private javax.swing.JLabel quanLyKhachHang_lbl;
    private javax.swing.JLabel sdt_lbl;
    private javax.swing.JTextField sdt_txt;
    private javax.swing.JLabel ten_lbl;
    private javax.swing.JTextField ten_txt;
    private javax.swing.JButton themKH_btn;
    private javax.swing.JButton themThuoc_btn1;
    private javax.swing.JButton them_btn;
    private javax.swing.JButton themcsv_btn;
    private javax.swing.JLabel thongTinKhachHang_lbl;
    private javax.swing.JButton tim_btn;
    private javax.swing.JTextField tim_txt;
    private javax.swing.JComboBox<String> tinhComboBox;
    private javax.swing.JLabel tinhThanh_lbl;
    // End of variables declaration//GEN-END:variables
    
    private void loadData() {
        try {
            FileReader reader = new FileReader("data/diaChi.Json");
            data = new JSONArray(new JSONTokener(reader));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Hàm hiển thị các tỉnh/thành phố vào tinhComboBox
    private void loadTinhComboBox() {
        tinhComboBox.removeAllItems();  // Xóa tất cả các mục hiện có
        tinhComboBox.addItem("--Chọn tỉnh thành--");

        for (int i = 0; i < data.length(); i++) {
            JSONObject tinh = data.getJSONObject(i);
            tinhComboBox.addItem(tinh.getString("Name"));
        }

        // Sự kiện khi chọn tỉnh/thành phố để load quận/huyện tương ứng
        tinhComboBox.addActionListener(e -> loadQuanComboBox());
    }

    // Hàm hiển thị quận/huyện tương ứng với tỉnh/thành phố đã chọn
    private void loadQuanComboBox() {
        quanComboBox.removeAllItems();  // Xóa tất cả các mục hiện có
        phuongComboBox.removeAllItems();  // Xóa phường khi thay đổi quận

        int selectedTinhIndex = tinhComboBox.getSelectedIndex() - 1; // Bỏ qua item "--Chọn tỉnh thành--"
        if (selectedTinhIndex >= 0) {
            JSONObject selectedTinh = data.getJSONObject(selectedTinhIndex);
            JSONArray districts = selectedTinh.getJSONArray("Districts");

            quanComboBox.addItem("--Chọn quận huyện--");
            for (int j = 0; j < districts.length(); j++) {
                JSONObject quan = districts.getJSONObject(j);
                quanComboBox.addItem(quan.getString("Name"));
            }

            // Sự kiện khi chọn quận/huyện để load phường/xã tương ứng
            quanComboBox.addActionListener(e -> loadPhuongComboBox());
        }
    }

    // Hàm hiển thị phường/xã tương ứng với quận/huyện đã chọn
    private void loadPhuongComboBox() {
        phuongComboBox.removeAllItems();  // Xóa tất cả các mục hiện có

        int selectedTinhIndex = tinhComboBox.getSelectedIndex() - 1;
        int selectedQuanIndex = quanComboBox.getSelectedIndex() - 1;
        if (selectedTinhIndex >= 0 && selectedQuanIndex >= 0) {
            JSONObject selectedTinh = data.getJSONObject(selectedTinhIndex);
            JSONArray districts = selectedTinh.getJSONArray("Districts");
            JSONObject selectedQuan = districts.getJSONObject(selectedQuanIndex);
            JSONArray wards = selectedQuan.getJSONArray("Wards");

            phuongComboBox.addItem("--Chọn phường xã--");
            for (int k = 0; k < wards.length(); k++) {
                JSONObject phuong = wards.getJSONObject(k);
                phuongComboBox.addItem(phuong.getString("Name"));
            }
        }
    }
}
