package GUI;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.awt.Color;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.FileReader;
import org.json.JSONTokener;

/**
 *
 * @author nguye
 */
public class NhanVien_GUI extends javax.swing.JPanel {

    private JSONArray data;

    /**
     * Creates new form NhanVien_GUI
     */
    public NhanVien_GUI() {
        initComponents();
        loadData();  // Tải dữ liệu từ file JSON khi khởi tạo
        loadTinhComboBox();  // Hiển thị dữ liệu vào tinhComboBox
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstPanel = new javax.swing.JPanel();
        west = new javax.swing.JPanel();
        maNhanVien_lbl = new javax.swing.JLabel();
        ma_txt = new javax.swing.JTextField();
        tenNhanVien_lbl = new javax.swing.JLabel();
        ten_txt = new javax.swing.JTextField();
        chucVu_lbl = new javax.swing.JLabel();
        nhanVien_cbo = new javax.swing.JComboBox<>();
        gioiTinh_lbl = new javax.swing.JLabel();
        gioiTinh_cbo = new javax.swing.JComboBox<>();
        center = new javax.swing.JPanel();
        email_lbl = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        sdt_lbl = new javax.swing.JLabel();
        sdt_txt = new javax.swing.JTextField();
        ngaySinh_lbl = new javax.swing.JLabel();
        ngayVaoLam_lbl = new javax.swing.JLabel();
        ngaySinh_date = new com.toedter.calendar.JDateChooser();
        ngayVaoLam_date = new com.toedter.calendar.JDateChooser();
        east = new javax.swing.JPanel();
        quanComboBox = new javax.swing.JComboBox<>();
        tinhThanh_lbl = new javax.swing.JLabel();
        tinhComboBox = new javax.swing.JComboBox<>();
        quanHuyen_lbl = new javax.swing.JLabel();
        phuongComboBox = new javax.swing.JComboBox<>();
        phuongXa_lbl = new javax.swing.JLabel();
        diaChi_lbl = new javax.swing.JLabel();
        quanLyNhanVien_lbl = new javax.swing.JLabel();
        lastPanel = new javax.swing.JPanel();
        them_btn = new javax.swing.JButton();
        sua_btn = new javax.swing.JButton();
        tim_txt = new javax.swing.JTextField();
        them_txt = new javax.swing.JButton();
        nhanVienScollPanel = new javax.swing.JScrollPane();
        nhanVien_table = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        firstPanel.setBackground(new java.awt.Color(255, 255, 255));
        firstPanel.setLayout(new java.awt.BorderLayout());

        west.setBackground(new java.awt.Color(255, 255, 255));

        maNhanVien_lbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        maNhanVien_lbl.setText("Mã nhân viên");

        ma_txt.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ma_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ma_txtActionPerformed(evt);
            }
        });

        tenNhanVien_lbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tenNhanVien_lbl.setText("Tên nhân viên");

        ten_txt.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ten_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ten_txtActionPerformed(evt);
            }
        });

        chucVu_lbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        chucVu_lbl.setText("Chức vụ");

        nhanVien_cbo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        nhanVien_cbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân Viên", "Quản Lý" }));
        nhanVien_cbo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        nhanVien_cbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanVien_cboActionPerformed(evt);
            }
        });

        gioiTinh_lbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        gioiTinh_lbl.setText("Giới tính");

        gioiTinh_cbo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        gioiTinh_cbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn giới tính--", "Nam", "Nữ" }));
        gioiTinh_cbo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        gioiTinh_cbo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout westLayout = new javax.swing.GroupLayout(west);
        west.setLayout(westLayout);
        westLayout.setHorizontalGroup(
            westLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(westLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(westLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chucVu_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gioiTinh_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(tenNhanVien_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maNhanVien_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(nhanVien_cbo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ma_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(ten_txt)
                    .addComponent(gioiTinh_cbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        westLayout.setVerticalGroup(
            westLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(westLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maNhanVien_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ma_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tenNhanVien_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ten_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chucVu_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nhanVien_cbo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gioiTinh_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gioiTinh_cbo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        firstPanel.add(west, java.awt.BorderLayout.WEST);

        center.setBackground(new java.awt.Color(255, 255, 255));
        center.setPreferredSize(new java.awt.Dimension(412, 294));

        email_lbl.setBackground(new java.awt.Color(255, 255, 255));
        email_lbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        email_lbl.setText("Email");

        email_txt.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });

        sdt_lbl.setBackground(new java.awt.Color(255, 255, 255));
        sdt_lbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        sdt_lbl.setText("Số điện thoại");

        sdt_txt.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        sdt_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdt_txtActionPerformed(evt);
            }
        });

        ngaySinh_lbl.setBackground(new java.awt.Color(255, 255, 255));
        ngaySinh_lbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ngaySinh_lbl.setText("Ngày sinh");

        ngayVaoLam_lbl.setBackground(new java.awt.Color(255, 255, 255));
        ngayVaoLam_lbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ngayVaoLam_lbl.setText("Ngày vào làm");

        ngaySinh_date.setBackground(new java.awt.Color(255, 255, 255));
        ngaySinh_date.setDateFormatString("dd-MM-yyyy");
        ngaySinh_date.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        ngayVaoLam_date.setBackground(new java.awt.Color(255, 255, 255));
        ngayVaoLam_date.setDateFormatString("dd-MM-yyyy");
        ngayVaoLam_date.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ngayVaoLam_date.setMaxSelectableDate(new java.util.Date(253370743282000L));

        east.setBackground(new java.awt.Color(255, 255, 255));
        east.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        quanComboBox.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn quận huyện--" }));
        quanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanComboBoxActionPerformed(evt);
            }
        });

        tinhThanh_lbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tinhThanh_lbl.setText("Tỉnh thành");

        tinhComboBox.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tinhComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn tỉnh thành--" }));

        quanHuyen_lbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanHuyen_lbl.setText("Quận huyện");

        phuongComboBox.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        phuongComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn phường xã--" }));
        phuongComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phuongComboBoxActionPerformed(evt);
            }
        });

        phuongXa_lbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        phuongXa_lbl.setText("Phường xã");

        diaChi_lbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        diaChi_lbl.setText("Địa chỉ");

        javax.swing.GroupLayout eastLayout = new javax.swing.GroupLayout(east);
        east.setLayout(eastLayout);
        eastLayout.setHorizontalGroup(
            eastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eastLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(eastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eastLayout.createSequentialGroup()
                        .addComponent(diaChi_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eastLayout.createSequentialGroup()
                        .addGroup(eastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quanHuyen_lbl)
                            .addGroup(eastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tinhComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(quanComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tinhThanh_lbl)
                            .addComponent(phuongXa_lbl))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eastLayout.createSequentialGroup()
                        .addComponent(phuongComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        eastLayout.setVerticalGroup(
            eastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eastLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(diaChi_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tinhThanh_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tinhComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quanHuyen_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(phuongXa_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phuongComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout centerLayout = new javax.swing.GroupLayout(center);
        center.setLayout(centerLayout);
        centerLayout.setHorizontalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerLayout.createSequentialGroup()
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sdt_txt)
                    .addComponent(email_txt)
                    .addComponent(sdt_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(email_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ngayVaoLam_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ngaySinh_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(centerLayout.createSequentialGroup()
                        .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ngayVaoLam_date, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ngaySinh_date, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(east, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        centerLayout.setVerticalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerLayout.createSequentialGroup()
                        .addComponent(sdt_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sdt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ngayVaoLam_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ngayVaoLam_date, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ngaySinh_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ngaySinh_date, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(east, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        ngayVaoLam_date.getAccessibleContext().setAccessibleDescription("");

        firstPanel.add(center, java.awt.BorderLayout.CENTER);

        quanLyNhanVien_lbl.setBackground(new java.awt.Color(255, 255, 255));
        quanLyNhanVien_lbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyNhanVien_lbl.setForeground(new java.awt.Color(72, 160, 255));
        quanLyNhanVien_lbl.setText("Quản lý nhân viên");
        firstPanel.add(quanLyNhanVien_lbl, java.awt.BorderLayout.NORTH);

        lastPanel.setBackground(new java.awt.Color(255, 255, 255));
        lastPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        them_btn.setBackground(new java.awt.Color(72, 160, 255));
        them_btn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        them_btn.setForeground(new java.awt.Color(255, 255, 255));
        them_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\NetBeansProjects\\CT-QUAN-LY-DU-AN-HIEU-THUOC-TAY\\QuanLyHieuThuoc\\image\\plus-24.png")); // NOI18N
        them_btn.setText("Thêm");
        them_btn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        sua_btn.setBackground(new java.awt.Color(72, 160, 255));
        sua_btn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        sua_btn.setForeground(new java.awt.Color(255, 255, 255));
        sua_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\NetBeansProjects\\CT-QUAN-LY-DU-AN-HIEU-THUOC-TAY\\QuanLyHieuThuoc\\image\\wrench-24.png")); // NOI18N
        sua_btn.setText("Sửa");
        sua_btn.setPreferredSize(new java.awt.Dimension(106, 34));
        sua_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sua_btnActionPerformed(evt);
            }
        });

        tim_txt.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tim_txt.setForeground(new java.awt.Color(189, 189, 189));
        tim_txt.setText("Mã nhân viên, tên nhân viên,...");
        tim_txt.setToolTipText("");
        tim_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tim_txtFocusGained(evt);
            }
        });
        tim_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tim_txtActionPerformed(evt);
            }
        });

        them_txt.setBackground(new java.awt.Color(72, 160, 255));
        them_txt.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        them_txt.setForeground(new java.awt.Color(255, 255, 255));
        them_txt.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\NetBeansProjects\\CT-QUAN-LY-DU-AN-HIEU-THUOC-TAY\\QuanLyHieuThuoc\\image\\magnifying-glass-3-24.png")); // NOI18N
        them_txt.setText("Tìm");

        javax.swing.GroupLayout lastPanelLayout = new javax.swing.GroupLayout(lastPanel);
        lastPanel.setLayout(lastPanelLayout);
        lastPanelLayout.setHorizontalGroup(
            lastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(them_btn)
                .addGap(18, 18, 18)
                .addComponent(sua_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tim_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(them_txt)
                .addContainerGap())
        );
        lastPanelLayout.setVerticalGroup(
            lastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lastPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tim_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(them_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sua_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        firstPanel.add(lastPanel, java.awt.BorderLayout.PAGE_END);

        add(firstPanel, java.awt.BorderLayout.PAGE_START);

        nhanVien_table.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        nhanVien_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Họ tên", "Giới tính", "Ngày sinh", "Số điện thoại", "Ngày vào làm", "Email", "Chức vụ", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        nhanVienScollPanel.setViewportView(nhanVien_table);

        add(nhanVienScollPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tim_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tim_txtFocusGained
        // TODO add your handling code here:
        if (tim_txt.getText().equals("Mã nhân viên, tên nhân viên,...")) {
            tim_txt.setText(""); // Xóa placeholder khi người dùng bắt đầu nhập
            tim_txt.setForeground(Color.BLACK); // Đặt màu văn bản về màu đen"
        }
    }//GEN-LAST:event_tim_txtFocusGained

    private void nhanVien_cboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanVien_cboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhanVien_cboActionPerformed

    private void ten_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ten_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ten_txtActionPerformed

    private void ma_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ma_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ma_txtActionPerformed

    private void phuongComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phuongComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phuongComboBoxActionPerformed

    private void quanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quanComboBoxActionPerformed

    private void sdt_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdt_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdt_txtActionPerformed

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtActionPerformed

    private void sua_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sua_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sua_btnActionPerformed

    private void tim_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tim_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tim_txtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel center;
    private javax.swing.JLabel chucVu_lbl;
    private javax.swing.JLabel diaChi_lbl;
    private javax.swing.JPanel east;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JTextField email_txt;
    private javax.swing.JPanel firstPanel;
    private javax.swing.JComboBox<String> gioiTinh_cbo;
    private javax.swing.JLabel gioiTinh_lbl;
    private javax.swing.JPanel lastPanel;
    private javax.swing.JLabel maNhanVien_lbl;
    private javax.swing.JTextField ma_txt;
    private com.toedter.calendar.JDateChooser ngaySinh_date;
    private javax.swing.JLabel ngaySinh_lbl;
    private com.toedter.calendar.JDateChooser ngayVaoLam_date;
    private javax.swing.JLabel ngayVaoLam_lbl;
    private javax.swing.JScrollPane nhanVienScollPanel;
    private javax.swing.JComboBox<String> nhanVien_cbo;
    private javax.swing.JTable nhanVien_table;
    private javax.swing.JComboBox<String> phuongComboBox;
    private javax.swing.JLabel phuongXa_lbl;
    private javax.swing.JComboBox<String> quanComboBox;
    private javax.swing.JLabel quanHuyen_lbl;
    private javax.swing.JLabel quanLyNhanVien_lbl;
    private javax.swing.JLabel sdt_lbl;
    private javax.swing.JTextField sdt_txt;
    private javax.swing.JButton sua_btn;
    private javax.swing.JLabel tenNhanVien_lbl;
    private javax.swing.JTextField ten_txt;
    private javax.swing.JButton them_btn;
    private javax.swing.JButton them_txt;
    private javax.swing.JTextField tim_txt;
    private javax.swing.JComboBox<String> tinhComboBox;
    private javax.swing.JLabel tinhThanh_lbl;
    private javax.swing.JPanel west;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        try {
            FileReader reader = new FileReader("data/diaChi.Json");
            data = new JSONArray(new JSONTokener(reader));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Hàm hiển thị các tỉnh/thành phố vào tinhComboBox
    private void loadTinhComboBox() {
        tinhComboBox.removeAllItems();  // Xóa tất cả các mục hiện có
        tinhComboBox.addItem("--Chọn tỉnh thành--");

        for (int i = 0; i < data.length(); i++) {
            JSONObject tinh = data.getJSONObject(i);
            tinhComboBox.addItem(tinh.getString("Name"));
        }

        // Sự kiện khi chọn tỉnh/thành phố để load quận/huyện tương ứng
        tinhComboBox.addActionListener(e -> loadQuanComboBox());
    }

    // Hàm hiển thị quận/huyện tương ứng với tỉnh/thành phố đã chọn
    private void loadQuanComboBox() {
        quanComboBox.removeAllItems();  // Xóa tất cả các mục hiện có
        phuongComboBox.removeAllItems();  // Xóa phường khi thay đổi quận

        int selectedTinhIndex = tinhComboBox.getSelectedIndex() - 1; // Bỏ qua item "--Chọn tỉnh thành--"
        if (selectedTinhIndex >= 0) {
            JSONObject selectedTinh = data.getJSONObject(selectedTinhIndex);
            JSONArray districts = selectedTinh.getJSONArray("Districts");

            quanComboBox.addItem("--Chọn quận huyện--");
            for (int j = 0; j < districts.length(); j++) {
                JSONObject quan = districts.getJSONObject(j);
                quanComboBox.addItem(quan.getString("Name"));
            }

            // Sự kiện khi chọn quận/huyện để load phường/xã tương ứng
            quanComboBox.addActionListener(e -> loadPhuongComboBox());
        }
    }

    // Hàm hiển thị phường/xã tương ứng với quận/huyện đã chọn
    private void loadPhuongComboBox() {
        phuongComboBox.removeAllItems();  // Xóa tất cả các mục hiện có

        int selectedTinhIndex = tinhComboBox.getSelectedIndex() - 1;
        int selectedQuanIndex = quanComboBox.getSelectedIndex() - 1;
        if (selectedTinhIndex >= 0 && selectedQuanIndex >= 0) {
            JSONObject selectedTinh = data.getJSONObject(selectedTinhIndex);
            JSONArray districts = selectedTinh.getJSONArray("Districts");
            JSONObject selectedQuan = districts.getJSONObject(selectedQuanIndex);
            JSONArray wards = selectedQuan.getJSONArray("Wards");

            phuongComboBox.addItem("--Chọn phường xã--");
            for (int k = 0; k < wards.length(); k++) {
                JSONObject phuong = wards.getJSONObject(k);
                phuongComboBox.addItem(phuong.getString("Name"));
            }
        }
    }
}
